name: Pull Request

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  pull_request_checks:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1
      - name: Install Fastlane
        run: gem install fastlane -no-rdoc --no-document
      - name: Install Ruby Dependencies
        run: bundle install
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Run Unit Test
        run: bundle exec fastlane unit_test
